[deps]
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashBootstrapComponents = "1b08a953-4be3-4667-9a23-fa6d05876a1e"
DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
